### ISSUE TITLE
[chore] Get rid of duplicate from `news_site`

### ISSUE THREAD

**Issue by sidharthshah** [fafadiatech/newscout_web#252]
There are few duplicates files specially few management commands

**Comment by yspanchal** [comment]
fixed in https://github.com/fafadiatech/newscout_web/pull/279

**Comment by Shivani-Padhye** [comment]
still getting this issue in more news.
 (http://www.newscout.in/news/article/kroger-rationing-sanitizers-amid-coronavirus-shopping-frenzy-1483830/)check this link.
